[system]
compatible=audiobox-rpi5
bootloader=barebox
statusfile=/etc/rauc/status.data

[keyring]
path=/etc/rauc/keyring.pem

[slot.app.0]
device=/opt/audiobox/app-slot-0
type=raw

[slot.app.1]
device=/opt/audiobox/app-slot-1
type=raw 